name: test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        include:
          - node-version: 16.x
            env:
              COVERAGE: 1
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run cover

      - name: Publish Coverage Report
        if: ${{ matrix.env.COVERAGE }}
        uses: codecov/codecov-action@v3

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: npm ci

      - name: npm login
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: publish
        run: npm publish
